### PR TITLE
SEO, seo card, personalized 404 page, Falcon added

### PR DESCRIPTION
**Pull request by darkRaspberry**
Changes according v1
--------------------------------------------------
 - SEO Rules added.
   - For Google
   - For Facebook
   - For Twitter
 - Inside `<head>` code is optimized.
 - SEO card added(personalized).
 - Falcon added(personalized).
 - Personalized 404 page added.
 - Front-end code optimized.

--------------------
No breaking changes introduced.

Abhay Kumar Verma

### CODE REVIEW

**Comment by darkRaspberry** [comment]
May introduce mob and tab version but can't promise things.

**Review by sidx8 — COMMENTED** [review]
nice work

**Review by sidx8 — CHANGES_REQUESTED** [review]
try changing the design to your liking for example images color scheme fonts since its a web design competition

**Comment by darkRaspberry** [comment]
I have designed the whole 404 error page. With my own design matching the enviroment.
The color scheme change require lots of work. That's a little impossible for me at this 2 days.
If You like my work merge.
I may create a new PR when more edit are ready.
I can't promise anything,

**Comment by sidx8** [comment]
ok ill merge but change the pull request to sidx8::web-design-competion-1 branch  instead to the master

**Comment by darkRaspberry** [comment]
Branch changed

**Comment by sidx8** [comment]
Good work Abhay i will merge this

**Pull request merged**
